version: "2"

run:
  deadline: 5m

issues:
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck

linters-settings:
  errcheck:
    exclude-functions:
    - (github.com/go-kit/log.Logger).Log
    - fmt.Fprintln
    - fmt.Fprint
