version: 2.1

orbs:
  go: circleci/go@2.2.4
  aws-ecr: circleci/aws-ecr@9.3.7
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  build-and-push:
    executor: aws-ecr/default
    steps:
     - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup
          region: us-west-2
          repo: jiralert
          tag: $CIRCLE_SHA1
          platform: linux/amd64,linux/arm64
          create_repo: true

workflows:
  build-and-push-prod:
    when:
      equal: [master, << pipeline.git.branch >>]
    jobs:
      - build-and-push:
          context:
          - prod
          - prod-us-west-2
  build-and-push-ops:
    # when:
    #   equal: [master, << pipeline.git.branch >>]
    jobs:
      - build-and-push:
          context:
          - ops