# TODO: Move to Onefootball ECR

name: build-docker

on:
  # release:
  #   types: [published]
  workflow_dispatch:

permissions:
  id-token: write # This is required for OIDC authentication to AWS ECR
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: linux-arm64-runner # Our self-hosted ARM runner
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go mod vendor
      - id: build-and-push-native-image
        uses: motain/onefootball-actions/docker-build-push-native@master
        with:
          mode: build-native
          tag: latest
          arch: ${{ matrix.arch }}
          secrets: |
            JIRA_TOKEN=${{ secrets.JIRA_TOKEN }}
